

export const formOptions = {
    homeFacility: [
        { value: "1 Bedroom Apartment", label: "1 Bedroom Apartment" },
        { value: "2 Bedroom Apartment", label: "2 Bedroom Apartment" },
        { value: "3 Bedroom Apartment", label: "3 Bedroom Apartment" },
        { value: "4 Bedroom Apartment", label: "4 Bedroom Apartment" },
        { value: "3 Bedroom Duplex", label: "3 Bedroom Duplex" },
        { value: "4 Bedroom Duplex", label: "4 Bedroom Duplex" },
        { value: "5 Bedroom Duplex", label: "5 Bedroom Duplex" },
    ],
    lightPoints: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "11", label: "11" },
        { value: "12", label: "12" },
        { value: "13", label: "13" },
        { value: "14", label: "14" },
        { value: "15", label: "15" },
        { value: "16", label: "16" },
        { value: "17", label: "17" },
        { value: "18", label: "18" },
        { value: "19", label: "19" },
        { value: "20", label: "20" },
        { value: "Others", label: "Others" },
    ],
    bulbType: [
        { value: "Traditional Bulbs", label: "Traditional Bulbs" },
        { value: "Led lights", label: "Led Lights" },
    ],
    securityLight: [
        { value: "Traditional Bulbs", label: "Traditional Bulbs" },
        { value: "Led lights", label: "Led Lights" },
        { value: "Flood lights", label: "Flood Lights" },
    ],
    conditioners: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    microwave: [
        { value: "Yes", label: "Yes" },
        { value: "No", label: "No" },
    ],
    chandelier: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    tvInches: [
        { value: "0", label: "0" },
        { value: "32 inches", label: "32 inches" },
        { value: "45 inches", label: "45 inches" },
        { value: "55 inches", label: "55 inches" },
        { value: "65 inches", label: "65 inches" },
        { value: "70 inches", label: "70 inches" },
        { value: "75 inches", label: "75 inches" },
        { value: "More", label: "More" },
    ],
    washingMachine: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    electricOven: [
        { value: "Yes", label: "Yes" },
        { value: "No", label: "No" },
    ],
    secLightNo: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    refrigerators: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    tvNumber: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    deepFreezers: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    waterHeaters: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    acCapacity: [
        { value: "0", label: "0" },
        { value: "1HP", label: "1HP" },
        { value: "1.5HP", label: "1.5HP" },
        { value: "2HP", label: "2HP" },
        { value: "3HP", label: "3HP" },
        { value: "4HP", label: "4HP" },
    ],
    waterPumps: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
    fans: [
        { value: "1", label: "1" },
        { value: "2", label: "2" },
        { value: "3", label: "3" },
        { value: "4", label: "4" },
        { value: "5", label: "5" },
        { value: "6", label: "6" },
        { value: "7", label: "7" },
        { value: "8", label: "8" },
        { value: "9", label: "9" },
        { value: "10", label: "10" },
        { value: "Others", label: "Others" },
    ],
};